name: Build and deploy for prod
on: [push]
jobs:
  android-build:
    name: Android main Build
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout repo from main branch
        uses: actions/checkout@v3
        with:
          ref: build-test
      - name: Install npm dependency
        run: npm install
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        env: # Or as an environment variable
          FLIPPER_VERSION: ${{ secrets.FLIPPER_VERSION }}
        run: |
          cd android
          ./gradlew build
      - name: Build Android JS Bundle
        run: |
          yarn run package-android
      - name: Delete Android build duplicate assets resource
        run: yarn run delete-pics
      - name: Install bundler
        run: |
          cd android
          gem install bundler
      - name: Install gem plugins
        run: |
          cd android
          bundle install
      - name: Run fastlane
        run: |
          cd android
          bundle exec fastlane build_qa

  # ios-build:
  #   name: iOS main Build
  #   runs-on: self-hosted
  #   steps:
  #     - name: Show self-hosted machine infomation
  #       run: uname -a
  #     - name: Cancel previous runs
  #       uses: styfle/cancel-workflow-action@0.9.1
  #     - name: Checkout repo from main branch
  #       uses: actions/checkout@v3
  #       with:
  #         ref: main
  #     - name: Install npm dependency
  #       run: yarn install
  #     - name: Cache cocoapods
  #       uses: actions/cache@v3
  #       with:
  #         path: /ios/Pods
  #         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pods-
  #     - name: Install pod dependency
  #       run: |
  #         cd ios
  #         bundle exec pod install
  #     - name: Build iOS JS Bundle
  #       run: |
  #         yarn run package-ios
  #     - name: Install bundler
  #       run: |
  #         cd ios
  #         gem install bundler
  #     - name: Install gem plugins
  #       run: |
  #         cd ios
  #         bundle install
  #     - name: Run fastlane
  #       run: |
  #         cd ios
  #         bundle exec fastlane build_testflight
